### ISSUE TITLE
Getting error while running through docker-compose

### ISSUE THREAD

**Issue by achyut1901** [ejhayes/bull-monitor#254]
this is my configuration:
```
bull-monitor:
    image: ejhayes/nodejs-bull-monitor:latest
    ports:
      - 8300:8300
    environment:
      REDIS_HOST: xxxxxxxxxxxx
      REDIS_PORT: 6379
      PORT: 8300
      BULL_WATCH_QUEUE_PREFIXES: multi
      UI: bull-master
```

Error:
```
bull-monitor_1                      | ReplyError
bull-monitor_1                      | ReplyError: ERR unknown command `config`, with args beginning with: `GET`, `notify-keyspace-events`,
bull-monitor_1                      |     at parseError (/app/node_modules/redis-parser/lib/parser.js:179:12)
bull-monitor_1                      |     at parseType (/app/node_modules/redis-parser/lib/parser.js:302:14)
```

While running docker-compose up i am getting below error.
![image](https://github.com/ejhayes/bull-monitor/assets/96162672/03b820c1-1773-4f5f-8ad9-8cf3be52febd)
